export const SEARCH_USERS = 'SEARCH_USERS'
export const SEARCH_USERS_SUCCESS = 'SEARCH_USERS_SUCCESS'
export const SEARCH_USERS_FAILURE = 'SEARCH_USERS_FAILURE'
export const ON_SEARCH_INPUT_CHANGE = 'ON_SEARCH_INPUT_CHANGE'
export const LOAD_MORE_USERS = 'LOAD_MORE_USERS'

export const FETCH_MORE_USERS = 'FETCH_MORE_USERS'
export const FETCH_MORE_USERS_SUCCESS = 'FETCH_MORE_USERS_SUCCESS'
export const FETCH_MORE_USERS_FAILURE = 'FETCH_MORE_USERS_FAILURE'

export const FETCH_USERS = 'FETCH_USERS'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE'
